[Icon Theme]
Name=Tarsila-icons
Comment=Papirus com retoques do Tarsila (disco azul, rede colorida)
Inherits=Papirus,hicolor
Directories=16x16/devices,16x16/places,22x22/devices,22x22/places,24x24/devices,24x24/places,32x32/devices,32x32/places,48x48/devices,48x48/places,64x64/devices,64x64/places

[16x16/devices]
Size=16
Context=Devices
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[22x22/devices]
Size=22
Context=Devices
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[24x24/devices]
Size=24
Context=Devices
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[32x32/devices]
Size=32
Context=Devices
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[48x48/devices]
Size=48
Context=Devices
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[64x64/devices]
Size=64
Context=Devices
Type=Fixed

[64x64/places]
Size=64
Context=Places
Type=Fixed
