Section "ServerFlags"
    Option "AutoAddGPU" "off"
EndSection

Section "Device"
    Identifier "MesonDisplay"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/by-path/platform-ff000000.vpu-card"
    Option "AccelMethod" "none"
EndSection
