Net/ThemeName "Xfce"
Net/IconThemeName "Tarsila-icons"
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
Gtk/FontName "Sans 10"
Gtk/CursorThemeName "Adwaita"
Gtk/CursorThemeSize 24
Gtk/DecorationLayout "close,maximize:"
Gtk/MenuImages 1
Gtk/ButtonImages 1
