Net/IconThemeName "Tarsila-icons"
Net/ThemeName "Tarsila"
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
Gtk/FontName "Inter 11"
Gtk/CursorThemeName "Adwaita"
Gtk/CursorThemeSize 32
Gtk/DecorationLayout "close,maximize:"
Gtk/MenuImages 1
Gtk/ButtonImages 1
